tasks: rcpl.tasks.dataset.*

experiment:
  class: rcpl.experiment.Experiment
  kwargs:
    json_path: "{DATA_DIR}/epsp_stress/measured/2023-11-23.json"
    crop_signal: [0, 681]

exp_representation: ['geom', 17, 20]
cpl_model_channels: ['epsp']
x_channels: ['stress']

model_factory:
    class: rcpl.cpl_models.maftr.MAFTrCPLModelFactory
    kwargs:
      params_bound:
        k0: [15, 250]
        κ1: [100, 10000]
        κ2: [0.00666666, 0.033333]
        κ3: [ 100, 1000 ]
        κ4: [ 0.02, 0.05 ]
        κ5: [ 10, 200 ]
        κ6: [ 0.02, 0.05 ]
        c1: [ 1000, 50000 ]
        c2: [ 10, 5000 ]
        c3: [ 10, 2000 ]
        c4: [ 10, 2000 ]
        a1: [ 0.000000001, 200 ]
        a2: [ 0.000000001, 200 ]
        a3: [ 0.000000001, 200 ]
        a4: [ 0.000000001, 200 ]
        aL: [ 0, 500 ]
      apriori_distribution_params:
        a_sum_bound: [100, 400]
        log_shift: 100
        scale_c: 1
      model_kwargs:
        dim: 4
        kappa_dim: 6

split: [0, 1000000, 1020000, 1120000]
n_samples_for_stats: 1000000

scale_type: 'standard'  # 'standard' or 'minmax'
