tasks: rcpl.tasks.dataset.*

exp_generator:
  class: rcpl.experiment.EpsPRandomExperimentGenerator
  kwargs:
    dist_type: beta
    epsp_dist_config:
      num_reversals: 43
      alpha: 2
      beta: 6
      return_same_chance: 0.2
      min_step: 0.0002
      bound: 0.007
    experiment_kwargs:
      crop_signal: [0, 681]

exp_representation: ['geom', 17, 20]
cpl_model_channels: ['epsp']
x_channels: ['stress', 'epsp']

model_factory:
    class: rcpl.cpl_models.maftr.MAFTrCPLModelFactory
    kwargs:
      params_bound:
        k0: [15, 250]
        κ1: [100, 10000]
        κ2: [0.00666666, 0.033333]
        c1: [1000, 10000]
        c2: [10, 2000]
        c3: [10, 2000]
        c4: [10, 2000]
        a1: [0.000000001, 200]
        a2: [0.000000001, 200]
        a3: [0.000000001, 200]
        a4: [0.000000001, 200]
        aL: [0, 500]
      apriori_distribution_params:
        a_sum_bound: [100, 400]
      model_kwargs:
        dim: 4
        kappa_dim: 2
        uses_log_c: false

split: [0, 1000000, 1020000, 1120000]
n_samples_for_stats: 1000000

scale_type: 'standard'  # 'standard' or 'minmax'
