tasks: rcpl.tasks.dataset.*

exp_generator:
  class: rcpl.experiment.EpsPRandomExperimentGenerator
  kwargs:
    epsp_uniform_params: [0.003, 0.005, 43]
    experiment_kwargs:
      crop_signal: [0, 681]

exp_representation: ['geom', 17, 20]

model_factory:
    class: rcpl.cpl_models.maftr.MAFTrCPLModelFactory
    kwargs:
      params_bound:
        k0: [15, 250]
        κ1: [100, 10000]
        κ2: [0.00666666, 0.033333]
        c1: [1000, 10000]
        c2: [10, 2000]
        c3: [10, 2000]
        c4: [10, 2000]
        a1: [0.000000001, 200]
        a2: [0.000000001, 200]
        a3: [0.000000001, 200]
        a4: [0.000000001, 200]
        aL: [0, 500]
      a_sum_bound: [0, 200]
      model_kwargs:
        dim: 4
        kappa_dim: 2

split: [0, 1000000, 1020000, 1120000]
n_samples_for_stats: 1000000

scale_type: 'standard'  # 'standard' or 'minmax'
