tasks: rcpl.tasks.dataset.*

experiment:
  class: rcpl.experiment.Experiment
  kwargs:
    json_path: "{DATA_DIR}/epsp_stress/measured/2023-11-23.json"
    crop_signal: [0, 681]

exp_representation: ['geom', 17, 20]
cpl_model_channels: ['epsp']
x_channels: ['stress']

model_factory:
    class: rcpl.cpl_models.maf.MAFCPLModelFactory
    kwargs:
      params_bound:
        k0: [15, 250]
        κ1: [100, 10000]
        κ2: [0.00666666, 0.033333]
        c1: [1000, 10000]
        c2: [50, 2000]
        c3: [50, 2000]
        c4: [50, 2000]
        a1: [0.000000001, 350]
        a2: [0.000000001, 350]
        a3: [0.000000001, 350]
        a4: [0.000000001, 350]
      a_sum_bound: [250, 350]
      model_kwargs:
        dim: 4
        kappa_dim: 2

split: [0, 1000000, 1020000, 1120000]
n_samples_for_stats: 1000000

scale_type: 'standard'  # 'standard' or 'minmax'
