tasks: rcpl.tasks.dataset.*

exp_generator:
  class: rcpl.experiment.RandomExperimentGenerator
  kwargs:
    epsp_uniform_params: [0.003, 0.005, 43]

exp_representation: ['geom', 15, 20]

model_factory:
    class: rcpl.cpl_models.maf.MAFCPLModelFactory
    kwargs:
      params_bound:
        k0: [15, 250]
        κ1: [100, 10000]
        κ2: [0.00666666, 0.033333]
        c1: [1000, 10000]
        c2: [50, 2000]
        c3: [50, 2000]
        c4: [50, 2000]
        a1: [0.000000001, 350]
        a2: [0.000000001, 350]
        a3: [0.000000001, 350]
        a4: [0.000000001, 350]
      a_sum_bound: [0, 350]
      model_kwargs:
        dim: 4
        kappa_dim: 2

split: [0, 1000000, 1020000, 1120000]
n_samples_for_stats: 1000000

scale_type: 'standard'  # 'standard' or 'minmax'
