tasks: rcpl.tasks.dataset.*

dim: 4
kappa_dim: 2
split: [0, 1000000, 1020000, 1050000]
random_experiment_params:
  uniform_params: [0.003, 0.005, 40]
  points_per_segment: 15
  method: "geometric"
  first_last_ratio: 20

n_samples_for_stats: 1000000
scale_type: 'standard'  # 'standard' or 'minmax'
