tasks: rcpl.tasks.processing.*
uses: "{CONFIGS_DIR}/dataset/2023-08-27.random.2_4.standard.yaml"

architecture: TTOptModel
takes_length: 603
prediction_is_scaled: false
takes_epsp: true
model_parameters:
  kappa_dim: 2
  dim: 4
  rank: 10
  ttopt_params:
    a: [15, 100, 0.006666666666666667, 1000, 50, 50, 50, 0.000000001, 0.000000001, 0.000000001, 0.000000001]  # Grid lower bound (number or list of len d)
    b: [250, 10000, 0.03333333333333333, 10000, 2000, 2000, 2000, 350, 350, 350, 350]
    p: 2  # The grid size factor (there will n=p^q points)
    q: 20  # The grid size factor (there will n=p^q points)
    evals: 100000  # Number of function evaluations
    name: Alpine  # Function name for log (this is optional)
    y_opt_real: 0.  # Real value of y-minima (y=f(x); this is for test)


is_trainable: false

# dataloader_params:
num_workers: 12
drop_last: true

valid_batch_size: 256
do_compile: false
run_dir: "random-standard"
run_name: "ttopt1-1"


x_metrics:
  x_l2: 'metrics.x_l2'

y_metrics:
  y_l2: 'metrics.y_l2'
